DROP TABLE deals CASCADE;
DROP TABLE eateries CASCADE;
DROP TABLE burgers CASCADE;


CREATE TABLE eateries 
(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE burgers
(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255),
  eatery_id INT8 REFERENCES eateries(id) ON DELETE CASCADE

);

CREATE TABLE deals 
(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255),
  day VARCHAR(255),
  eatery_id INT8 REFERENCES eateries(id) ON DELETE CASCADE
);


